export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'
export const CLEAR_MAP = 'CLEAR_MAP'

//JOB
export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR'

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'

export const SET_EDIT_JOB = 'SET_EDIT_JOB'

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN'

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN'
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR'

//STATS
export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'

//USER
export const GET_USERS_BEGIN = 'GET_USERS_BEGIN'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'

export const DELETE_USER_BEGIN = 'DELETE_USER_BEGIN'

export const SET_EDIT_USER = 'SET_EDIT_USER'
export const EDIT_USER_BEGIN = 'EDIT_USER_BEGIN'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR'
//EVENTS
export const CREATE_EVENT_BEGIN = 'CREATE_EVENT_BEGIN'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR'

export const GET_EVENTS_BEGIN = 'GET_EVENTS_BEGIN'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'

export const DELETE_EVENT_BEGIN = 'DELETE_EVENT_BEGIN'

export const SET_EDIT_EVENT = 'SET_EDIT_EVENT'
export const EDIT_EVENT_BEGIN = 'EDIT_EVENT_BEGIN'
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'
export const EDIT_EVENT_ERROR = 'EDIT_EVENT_ERROR'

//ACTIVITIES
export const CREATE_ACTIVITY_BEGIN = 'CREATE_ACTIVITY_BEGIN'
export const CREATE_ACTIVITY_SUCCESS = 'CREATE_ACTIVITY_SUCCESS'
export const CREATE_ACTIVITY_ERROR = 'CREATE_ACTIVITY_ERROR'

export const GET_ACTIVITIES_BEGIN = 'GET_ACTIVITIES_BEGIN'
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS'

export const DELETE_ACTIVITY_BEGIN = 'DELETE_ACTIVITY_BEGIN'

export const SET_EDIT_ACTIVITY = 'SET_EDIT_ACTIVITY'
export const EDIT_ACTIVITY_BEGIN = 'EDIT_ACTIVITY_BEGIN'
export const EDIT_ACTIVITY_SUCCESS = 'EDIT_ACTIVITY_SUCCESS'
export const EDIT_ACTIVITY_ERROR = 'EDIT_ACTIVITY_ERROR'

export const GET_SINGLE_EVENT = 'GET_SINGLE_EVENT'

export const CHANGE_EVENT_ID_SUCCESS = 'CHANGE_EVENT_ID_SUCCESS'

export const CLEAR_ACTIVITY = 'CLEAR_ACTIVITY'